@256
D=A
@SP
M=D
// --- BOOTSTRAP: Call Sys.init ---
@Sys.init$ret.0
D=A
@SP
A=M
M=D
@SP
M=M+1
@LCL
D=M
@SP
A=M
M=D
@SP
M=M+1
@ARG
D=M
@SP
A=M
M=D
@SP
M=M+1
@THIS
D=M
@SP
A=M
M=D
@SP
M=M+1
@THAT
D=M
@SP
A=M
M=D
@SP
M=M+1
@SP
D=M
@5
D=D-A
@ARG
M=D
@SP
D=M
@LCL
M=D
@Sys.init
0;JMP
(Sys.init$ret.0)
// ------------------------------------------------------------------------
//                                  Sys.vm                                 
// ------------------------------------------------------------------------
// // This file is part of www.nand2tetris.org
// // and the book "The Elements of Computing Systems"
// // by Nisan and Schocken, MIT Press.
// // File name: projects/8/FunctionCalls/FibonacciElement/Sys.vm
// 
// // Containts one function: Sys.init.
// 
// // Pushes a constant n onto the stack, and calls the Main.fibonacii
// // function, which computes the n'th element of the Fibonacci series.
// // Note that by convention, the Sys.init function is called "automatically" 
// // by the bootstrap code generated by the VM translator.
// function Sys.init 0
(Sys.init)
//     // Computes fibonacci(4)
// 	push constant 4
@4
D=A
@SP
A=M
M=D
@SP
M=M+1
// 	// Calls the function, informing that one argument was pushed onto the stack
// 	call Main.fibonacci 1
@Main.fibonacci$ret.1
D=A
@SP
A=M
M=D
@SP
M=M+1
@LCL
D=M
@SP
A=M
M=D
@SP
M=M+1
@ARG
D=M
@SP
A=M
M=D
@SP
M=M+1
@THIS
D=M
@SP
A=M
M=D
@SP
M=M+1
@THAT
D=M
@SP
A=M
M=D
@SP
M=M+1
@SP
D=M
@6
D=D-A
@ARG
M=D
@SP
D=M
@LCL
M=D
@Main.fibonacci
0;JMP
(Main.fibonacci$ret.1)
// label END  
(END)
// 	goto END  // loops infinitely
@END
0;JMP
// ------------------------------------------------------------------------
//                                 Main.vm                                 
// ------------------------------------------------------------------------
// // This file is part of www.nand2tetris.org
// // and the book "The Elements of Computing Systems"
// // by Nisan and Schocken, MIT Press.
// // File name: projects/8/FunctionCalls/FibonacciElement/Main.vm
// 
// // Contains one function: Main.fibonacci.
// 
// // Computes the n'th element of the Fibonacci series, recursively.
// // n is given in argument[0]. Called by the Sys.init function 
// // (part of the Sys.vm file), which sets argument[0] to an input
// // value and then calls Main.fibonacci.
// function Main.fibonacci 0
(Main.fibonacci)
// 	push argument 0
@0
D=A
@2
A=M
A=D+A
D=M
@SP
A=M
M=D
@SP
M=M+1
// 	push constant 2
@2
D=A
@SP
A=M
M=D
@SP
M=M+1
// 	lt                     
@SP
M=M-1
A=M
D=M
A=A-1
D=M-D
@COMP_TRUE_2
D;JLT
@SP
A=M-1
M=0
@COMP_END_2
0;JMP
(COMP_TRUE_2)
@SP
A=M-1
M=-1
(COMP_END_2)
// 	if-goto N_LT_2        
@0
AM=M-1
D=M
@N_LT_2
D;JNE
// 	goto N_GE_2
@N_GE_2
0;JMP
// label N_LT_2               // if n < 2 returns n
(N_LT_2)
// 	push argument 0        
@0
D=A
@2
A=M
A=D+A
D=M
@SP
A=M
M=D
@SP
M=M+1
// 	return
@LCL
D=M
@R13
M=D
@5
A=D-A
D=M
@R14
M=D
@SP
M=M-1
A=M
D=M
@ARG
A=M
M=D
@ARG
D=M+1
@SP
M=D
@R13
D=M
@1
A=D-A
D=M
@THAT
M=D
@R13
D=M
@2
A=D-A
D=M
@THIS
M=D
@R13
D=M
@3
A=D-A
D=M
@ARG
M=D
@R13
D=M
@4
A=D-A
D=M
@LCL
M=D
@R14
A=M
0;JMP
// label N_GE_2               // if n >= 2 returns fib(n - 2) + fib(n - 1)
(N_GE_2)
// 	push argument 0
@0
D=A
@2
A=M
A=D+A
D=M
@SP
A=M
M=D
@SP
M=M+1
// 	push constant 2
@2
D=A
@SP
A=M
M=D
@SP
M=M+1
// 	sub
@SP
M=M-1
A=M
D=M
A=A-1
M=M-D
// 	call Main.fibonacci 1  // computes fib(n - 2)
@Main.fibonacci$ret.3
D=A
@SP
A=M
M=D
@SP
M=M+1
@LCL
D=M
@SP
A=M
M=D
@SP
M=M+1
@ARG
D=M
@SP
A=M
M=D
@SP
M=M+1
@THIS
D=M
@SP
A=M
M=D
@SP
M=M+1
@THAT
D=M
@SP
A=M
M=D
@SP
M=M+1
@SP
D=M
@6
D=D-A
@ARG
M=D
@SP
D=M
@LCL
M=D
@Main.fibonacci
0;JMP
(Main.fibonacci$ret.3)
// 	push argument 0
@0
D=A
@2
A=M
A=D+A
D=M
@SP
A=M
M=D
@SP
M=M+1
// 	push constant 1
@1
D=A
@SP
A=M
M=D
@SP
M=M+1
// 	sub
@SP
M=M-1
A=M
D=M
A=A-1
M=M-D
// 	call Main.fibonacci 1  // computes fib(n - 1)
@Main.fibonacci$ret.4
D=A
@SP
A=M
M=D
@SP
M=M+1
@LCL
D=M
@SP
A=M
M=D
@SP
M=M+1
@ARG
D=M
@SP
A=M
M=D
@SP
M=M+1
@THIS
D=M
@SP
A=M
M=D
@SP
M=M+1
@THAT
D=M
@SP
A=M
M=D
@SP
M=M+1
@SP
D=M
@6
D=D-A
@ARG
M=D
@SP
D=M
@LCL
M=D
@Main.fibonacci
0;JMP
(Main.fibonacci$ret.4)
// 	add                    // returns fib(n - 1) + fib(n - 2)
@SP
M=M-1
A=M
D=M
A=A-1
M=D+M
// 	return
@LCL
D=M
@R13
M=D
@5
A=D-A
D=M
@R14
M=D
@SP
M=M-1
A=M
D=M
@ARG
A=M
M=D
@ARG
D=M+1
@SP
M=D
@R13
D=M
@1
A=D-A
D=M
@THAT
M=D
@R13
D=M
@2
A=D-A
D=M
@THIS
M=D
@R13
D=M
@3
A=D-A
D=M
@ARG
M=D
@R13
D=M
@4
A=D-A
D=M
@LCL
M=D
@R14
A=M
0;JMP
